Document: virt-create
Title: Debian virt-create Manual
Author: <insert document author here>
Abstract: This manual describes what virt-create is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/virt-create/virt-create.sgml.gz

Format: postscript
Files: /usr/share/doc/virt-create/virt-create.ps.gz

Format: text
Files: /usr/share/doc/virt-create/virt-create.text.gz

Format: HTML
Index: /usr/share/doc/virt-create/html/index.html
Files: /usr/share/doc/virt-create/html/*.html
